import React from "react";


export const metadata = {
    title: 'Nexjs Crash course',
    description: 'Generated by create next app',
    keywords: "web development, web design"
}

const AboutPage = () => {
    return <div>
        <h1>Welcome To Traversy Meida</h1>
        <p>
            Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quos ipsa consequatur praesentium,
            natus vero autem veritatis doloremque, deleniti maxime illum cumque voluptate placeat
            corporis sapiente tempore dicta? Ad, ipsa repellendus?
        </p>
    </div>;
};

export default AboutPage;
