import { Poppins } from 'next/font/google'
import Header from './components/Header'
import './globals.css'

const poppins = Poppins({
  weight: ["400", "600"],
  subsets: ['latin']
})

export const metadata = {
  title: 'Nexjs Crash course',
  description: 'Generated by create next app',
  keywords: "web development, web design"
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header/>
        <main className='container'>
          {children}
        </main>
      </body>
    </html>
  )
}
